PUT http://localhost:3001/api/movies/632fa951246dc37e0f45599b
Content-Type: application/json

{
  "title":"Star Wars IV. Return of the Jedi - UPDATED",
  "genreId": "632fa87fea0b9264e40a3322",
  "numberInStock": 12,
  "dailyRentalRate": 7
}